VokabelnBeiEingabeTemporärSpeichernFürBearbeiten:
TempDeutsch1=%Deutsch1%
TempDeutsch2=%Deutsch2%
TempDeutsch3=%Deutsch3%
TempEnglisch1=%Englisch1%
TempEnglisch2=%Englisch2%
TempEnglisch3=%Englisch3%
TempKommentarDeutsch=%KommentarDeutsch%
TempKommentarEnglisch=%KommentarEnglisch%
return

VokabelnBeiEingabeTemporärSpeichernFürHinzufügen:
Temp2Deutsch1=%Deutsch1%
Temp2Deutsch2=%Deutsch2%
Temp2Deutsch3=%Deutsch3%
Temp2Englisch1=%Englisch1%
Temp2Englisch2=%Englisch2%
Temp2Englisch3=%Englisch3%
Temp2KommentarDeutsch=%KommentarDeutsch%
Temp2KommentarEnglisch=%KommentarEnglisch%
return